GET http://localhost:8081/api/tickets
Accept: application/json

###
GET http://localhost:8081/api/tickets/13
Accept: application/json

###
POST http://localhost:8081/api/tickets
Content-Type: application/json

{
  "fulfillmentPeriod": {
    "dateOfNotification": "2021-08-08",
    "dateOfCompletion": "2021-08-09"
  },
  "partnerId": 1,
  "description": "string",
  "ticketGroupId": 1,
  "descriptionOfSolution": "string",
  "workHours": 0,
  "reportId": "string"
}
###
POST http://localhost:8081/api/tickets/8/materials
Content-Type: application/json

{
  "name": "50HFL6014",
  "price": "125000"
}
###
DELETE http://localhost:8081/api/tickets/10
Accept: application/json

###
DELETE http://localhost:8081/api/tickets/8/materials
Accept: application/json

###
